keys:
  - &YunAir age1upak4x3s6v8j4dk2m52ad6phrf3sw59qtyyq7a9j2kjhtm3g9y3qm6f4tk
  - &YuMac age1upak4x3s6v8j4dk2m52ad6phrf3sw59qtyyq7a9j2kjhtm3g9y3qm6f4tk
creation_rules:
  - path_regex: secrets/YunAir\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *YunAir
  - path_regex: secrets/YuMac\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *YuMac
  - path_regex: secrets/common\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *YunAir
          - *YuMac
